// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5-6HT-64XMxcwTQKFoBzp_WB58rajZjA',
    appId: '1:1057721621803:web:aa1a0436bb713a1166796e',
    messagingSenderId: '1057721621803',
    projectId: 'instantaid-9ce39',
    authDomain: 'instantaid-9ce39.firebaseapp.com',
    storageBucket: 'instantaid-9ce39.firebasestorage.app',
    measurementId: 'G-RT0W14P76T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPRoYCR9M3NRrIyyQazCVZPjuFf5egIpk',
    appId: '1:1057721621803:ios:466449e0fc1c7be466796e',
    messagingSenderId: '1057721621803',
    projectId: 'instantaid-9ce39',
    storageBucket: 'instantaid-9ce39.firebasestorage.app',
    iosBundleId: 'com.example.instantAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPRoYCR9M3NRrIyyQazCVZPjuFf5egIpk',
    appId: '1:1057721621803:ios:466449e0fc1c7be466796e',
    messagingSenderId: '1057721621803',
    projectId: 'instantaid-9ce39',
    storageBucket: 'instantaid-9ce39.firebasestorage.app',
    iosBundleId: 'com.example.instantAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5-6HT-64XMxcwTQKFoBzp_WB58rajZjA',
    appId: '1:1057721621803:web:ed835ad70bc603cb66796e',
    messagingSenderId: '1057721621803',
    projectId: 'instantaid-9ce39',
    authDomain: 'instantaid-9ce39.firebaseapp.com',
    storageBucket: 'instantaid-9ce39.firebasestorage.app',
    measurementId: 'G-X2HYMEYTL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxFW88pX8EJKULlXNuVW6M5VibA2K2W5I',
    appId: '1:1057721621803:android:4b8432cbfed5edae66796e',
    messagingSenderId: '1057721621803',
    projectId: 'instantaid-9ce39',
    storageBucket: 'instantaid-9ce39.firebasestorage.app',
  );

}